# Generated by Django 3.2.16 on 2023-08-11 16:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_group', models.CharField(max_length=3)),
                ('priority', models.IntegerField(default=0)),
                ('last_rsv', models.DateTimeField(blank=True, null=True)),
                ('base_fare', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('p_line_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('passenger_hp', models.CharField(blank=True, max_length=10, null=True)),
                ('favorite_places', models.JSONField(blank=True, null=True)),
                ('use_server', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('departing', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('arriving', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='沒有需求', max_length=255)),
                ('to_rsv', models.BooleanField(default=False)),
                ('current_driver', models.CharField(blank=True, max_length=255)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('p_line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goddess_taxi_server.passengers')),
            ],
        ),
        migrations.CreateModel(
            name='RideRSV',
            fields=[
                ('rsv_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_group', models.CharField(blank=True, max_length=3, null=True)),
                ('d_line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('p_line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('departing', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('arriving', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_route', models.BinaryField()),
                ('route_map', models.TextField(blank=True, max_length=5000, null=True)),
                ('travel_distance', models.FloatField()),
                ('travel_time', models.FloatField()),
                ('travel_fare', models.FloatField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goddess_taxi_server.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('d_line_id', models.CharField(blank=True, max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_hp', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('car_no', models.CharField(blank=True, max_length=20, null=True)),
                ('car_desc', models.CharField(blank=True, max_length=20, null=True)),
                ('is_online', models.BooleanField()),
                ('current_location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('current_group', models.CharField(blank=True, max_length=3, null=True)),
                ('current_rsv', models.CharField(blank=True, max_length=8, null=True)),
                ('driver_group', models.ManyToManyField(to='goddess_taxi_server.DriverGroup')),
            ],
        ),
    ]
