# Generated by Django 3.2.16 on 2023-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess_taxi_server', '0002_alter_riderequest_current_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='use_server',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
