# Generated by Django 3.2.16 on 2023-08-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess_taxi_server', '0003_alter_passengers_use_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='use_server',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='current_driver',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
