# Generated by Django 3.2.16 on 2023-08-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goddess_taxi_server', '0004_auto_20230814_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivergroup',
            name='driver_group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ridersv',
            name='driver_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goddess_taxi_server.drivergroup'),
            preserve_default=False,
        ),
    ]
