# Generated by Django 3.2.16 on 2023-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess_taxi_server', '0005_auto_20230814_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
