# Generated by Django 3.2.16 on 2023-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess_taxi_server', '0006_alter_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_desc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
